Here be Dragons
Project-disABLEd/frontend pull request #26
Opened 2020-04-29 20:02 UTC by jaanonim

2020-04-29 20:04 UTC, jaanonim commented
I added 2 lines of code that nobody has added to since the last 2 months.

Seriously, I am fixing this stupid zoom button.

2020-05-08 19:12 UTC, Wuzado requested changes
This PR doesn't introduce many real changes, but gives some food for thought and ideas how to improve the site.

2020-05-08 19:12 UTC, Wuzado commented on src/components/MainMap.vue
> +      }"
It already is implemented though in the commit eb85a03? On line 14: 
`<l-control-zoom position="bottomright"></l-control-zoom>`

Its position is set in a clearer HTML-style attribute.

2020-05-08 19:12 UTC, Wuzado commented on src/components/DisabilitiesDesc.vue
> +            <b-icon style="color:red;" v-else-if="levelOfSupport === -1" class="fas fa-thumbs-down"></b-icon>
This code change is actually quite valid, but here, logically, it shouldn't ever, ever have two values at once.

2020-05-08 19:12 UTC, Wuzado commented on src/store/store.js
> +        "127.0.0.1:8000" + "/points/" + currentID,
Same as line 57.

2020-05-08 19:12 UTC, Wuzado commented on src/store/store.js
> +        "127.0.0.1:8000" + "/points/",
Why are you setting the hostname like that? You should manually set it as a env var.

(Hint: .env files)

2020-05-08 19:12 UTC, Wuzado commented on src/components/Navbar.vue
> +          src="./../assets/logo_full.png"
Webpack and builder software correctly resolves the path later, during the (both dev and prod) build stage.

2020-05-08 19:12 UTC, Wuzado commented on src/components/MyMarker.vue
> +  },
Why is this even here? There isn't a single usage of this anywhere in the project files.

2020-05-08 19:12 UTC, Wuzado commented on src/components/MainMap.vue
> +      }"
I might have not deployed it correctly last time though. I re-deployed it for now, and I am looking into possibilities of CD on the master branch.

2020-05-08 19:14 UTC, Wuzado commented
This PR will be closed after :
* [] introducing CD
* [] changing v-if's to v-else-if's

Also, please, don't use whatthecommit.com for your commit messages. (Yes, I know about squashing)

2020-05-15 17:30 UTC, closed without merging